version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
