name: "Repository Visualiser"
description: "Visualise the repository structure"
author: "Jack Plowman"

runs:
  using: "docker"
  image: "./Dockerfile"
  env:
    GITHUB_ACTION: "true"
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} }}
