name: "Pull Request Tasks"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read

jobs:
  common-pull-request-tasks:
    name: Common Pull Request Tasks
    permissions:
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-pull-request-tasks.yml@cb8bab5e91314b79b7aefabab7d1a44b1fc9f5d6 # v2025.05.17.03
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
